services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "9898:9898"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/authservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - springboot-network

  db:
    image: mysql:8.3.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=authservice
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - springboot-network

volumes:
  mysql-data:

networks:
  springboot-network:
    driver: bridge

